### ISSUE TITLE
Failed to load from: null

### ISSUE THREAD

**Issue by endumiuz** [endumiuz/Luppio-gregtech#50]
MCU Console
`Failed to load from: null (stacktrace in MCUpdater log)`

MCUpdater.log.0
```
2015-08-04 22:26:31 [INFO] [MCUpdater] Activate interlocks!
2015-08-04 22:26:31 [INFO] [MCUpdater] Dynatherms connected!
2015-08-04 22:26:31 [INFO] [MCUpdater] Infracells up!
2015-08-04 22:26:31 [SEVERE] [MCUpdater] Failed to load from: null
java.lang.NullPointerException
	at org.mcupdater.util.ServerPackParser.readXmlFromUrl(ServerPackParser.java:48)
	at org.mcupdater.gui.MainForm.refreshInstanceList(MainForm.java:772)
	at org.mcupdater.gui.MainForm.settingsChanged(MainForm.java:928)
	at org.mcupdater.gui.MainForm.<init>(MainForm.java:126)
	at org.mcupdater.gui.Main$1.run(Main.java:82)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
2015-08-04 22:26:32 [INFO] [MCUpdater] Megathrusters are go!
2015-08-04 22:26:32 [INFO] [MCUpdater] Selection changed to: luppio-gregtech
```

MCU-API.log.0
```
2015-08-04 22:26:30 [INFO] [MCU-API] Initializing DownloadCache in C:\Users\***\AppData\Roaming\.MCUpdater\cache
2015-08-04 22:26:30 [FINE] [MCU-API] Took 278ms to load md5.dat
2015-08-04 22:26:30 [FINEST] [MCU-API] MCUpdater intialized with path: C:\Users\***\AppData\Roaming\.MCUpdater
2015-08-04 22:26:30 [INFO] [MCU-API] Instance root changed to: C:\Users\***\\AppData\Roaming\.MCUpdater\instances
2015-08-04 22:26:31 [FINE] [MCU-API] readXMLFromUrl(null)
2015-08-04 22:26:31 [FINE] [MCU-API] readXMLFromUrl(http://luppio.se/Luppio-GregTech.xml)
2015-08-04 22:26:31 [FINE] [MCU-API] luppio-gregtech: format=2
2015-08-04 22:26:31 [FINE] [MCU-API] readXMLFromUrl(http://files.mcupdater.com/example/forge.php?mc=1.7.10&forge=10.13.4.1492)
2015-08-04 22:26:31 [FINE] [MCU-API] forge: format=2
2015-08-04 22:26:32 [FINE] [MCU-API] readXMLFromUrl(http://luppio.se/ServerPacks/Luppio-GregTech/base.xml)
2015-08-04 22:26:32 [FINE] [MCU-API] base: format=2
2015-08-04 22:26:32 [FINE] [MCU-API] readXMLFromUrl(http://luppio.se/ServerPacks/Luppio-GregTech/2015-08-04.xml)
2015-08-04 22:26:32 [FINE] [MCU-API] 2015-08-04: format=2
2015-08-04 22:26:32 [INFO] [MCU-API] Instance root changed to: C:\Users\***\AppData\Roaming\.MCUpdater\instances
```

**Comment by endumiuz** [comment]
Seems to have been solved by deleting the .MCUpdater directory
